services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: recipe-db
    ports:
      - '5432:5432'
    expose:
      - '5432'
